---
title: "03_Models"
author: "Sglatt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
if (!require("dplyr")) {
  install.packages("dplyr")
  require("dplyr")
}
if (!require("tidyverse")) {
  install.packages("tidyverse")
  require("tidyverse")
}
if (!require("psych")) {
  install.packages("psych")
  require("psych")
}
if (!require("lme4")) {
  install.packages("lme4")
  require("lme4")
}
if (!require("lmerTest")) {
  install.packages("lmerTest")
  require("lmerTest")
}
if (!require("afex")) {
  install.packages("afex")
  require("afex")
}
if (!require("optimx")) {
  install.packages("optimx")
  require("optimx")
}
if (!require("sjPlot")) {
  install.packages("sjPlot")
  require("sjPlot")
}
if (!require("report")) {
  install.packages("report")
  require("report")
}
if (!require("apaTables")) {
  install.packages("apaTables")
  require("apaTables")
}
```

# Data 
```{r}
# Import stress data - from 01_Data
long_df_final <- read.csv("01_Output/long_stress_ratings_2025-07-15.csv")
colnames(long_df_final)

# Make folder for output
if (!dir.exists("03_Output")) {
  dir.create("03_Output")
}
```

# Set reference points for aggregate models
```{r}
long_df_final$AgeGroupCollapsed <- factor(long_df_final$AgeGroupCollapsed)
long_df_final$AgeGroupCollapsed <- relevel(long_df_final$AgeGroupCollapsed, ref = "Child/Teen/Young Adult")
```

# Null models
```{r null models}
# Null model with the general impact score
null_model_general <- lmer(
  GeneralImpactScore ~ 1
    + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
)
summary(null_model_general)

# Null model with the military impact score (remove people who are N/A)
null_model_military <- glmer(
  MilitaryImpactScoreBinary ~
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

summary(null_model_military)

tab_model(
  null_model_general,
  null_model_military
)
```

# models with age
```{r models with age}
long_df_final %>%
  filter(MilitaryImpactScoreBinary != 3) %>%
  group_by(AgeGroup, MilitaryImpactScoreBinary) %>%
  summarise(n = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = MilitaryImpactScoreBinary, values_from = n, values_fill = 0) %>%
  rename(NotImpactful = `0`, Impactful = `1`)

unique(long_df_final$AgeGroup)

# Age model with the general impact score and all age groups
main_model_general <- lmer(
  GeneralImpactScore ~
    AgeGroup +
    #   years_since_discharge +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
)
summary(main_model_general)

# Age model with the military impact score and all age groups
main_model_military <- glmer(
  MilitaryImpactScoreBinary ~
    AgeGroup +
    #  years_since_discharge +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)
summary(main_model_military)

# Age model with the general impact score and collapsed age groups
main_model_general_collapse <- lmer(
  GeneralImpactScore ~
    AgeGroupCollapsed +
    #  years_since_discharge +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
)
summary(main_model_general_collapse)

# Age model with the military impact score and collapsed age groups
main_model_military_collapse <- glmer(
  MilitaryImpactScoreBinary ~
    AgeGroupCollapsed +
    # years_since_discharge +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)
summary(main_model_military_collapse)


tab_model(
  main_model_general,
  main_model_military,
  main_model_general_collapse,
  main_model_military_collapse
)
```

# Null models with personality (PID-5)
```{r pid5}
#### General impact models, independently ####
model_pid_total_general <- lmer(
  GeneralImpactScore ~ PID_total_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]
)

model_na_general <- lmer(
  GeneralImpactScore ~ PID_Negative_Affect_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]
)

model_detachment_general <- lmer(
  GeneralImpactScore ~ PID_Detachment_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]
)

model_antagonism_general <- lmer(
  GeneralImpactScore ~ PID_Antagonism_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]
)

model_disinhibition_general <- lmer(
  GeneralImpactScore ~ PID_Disinhibition_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]
)

model_psychoticism_general <- lmer(
  GeneralImpactScore ~ PID_Psychoticism_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]
)

tab_model(
  model_pid_total_general,
  model_na_general,
  model_detachment_general,
  model_antagonism_general,
  model_disinhibition_general,
  model_psychoticism_general
)

#### Military impact models, independently ####

model_pid_total_military <- glmer(
  MilitaryImpactScoreBinary ~ PID_total_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

model_na_military <- glmer(
  MilitaryImpactScoreBinary ~ PID_Negative_Affect_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

model_detachment_military <- glmer(
  MilitaryImpactScoreBinary ~ PID_Detachment_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

model_antagonism_military <- glmer(
  MilitaryImpactScoreBinary ~ PID_Antagonism_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

model_disinhibition_military <- glmer(
  MilitaryImpactScoreBinary ~ PID_Disinhibition_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

model_psychoticism_military <- glmer(
  MilitaryImpactScoreBinary ~ PID_Psychoticism_SUM + (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

tab_model(
  model_pid_total_military,
  model_na_military,
  model_detachment_military,
  model_antagonism_military,
  model_disinhibition_military,
  model_psychoticism_military
)

#### General impact model, PID-5 together ####

model_general_pid5 <- lmer(
  GeneralImpactScore ~
    PID_Negative_Affect_SUM +
    PID_Detachment_SUM +
    PID_Antagonism_SUM +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]
)

#### Military impact model, PID-5 together ####

model_military_pid5 <- glmer(
  MilitaryImpactScoreBinary ~
    PID_Negative_Affect_SUM +
    PID_Detachment_SUM +
    PID_Antagonism_SUM +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

tab_model(model_general_pid5, model_military_pid5)
```

```{r ipo}
#### IPO General impact model, together ####

model_general_ipor <- lmer(
  GeneralImpactScore ~
    IPOr_PDID_SUM +
    IPOr_RT_SUM +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]
)

#### IPO Military impact model, together ####

model_military_ipor <- glmer(
  MilitaryImpactScoreBinary ~
    IPOr_PDID_SUM +
    IPOr_RT_SUM +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

tab_model(model_general_ipor, model_military_ipor)
```

```{r pf}
#### PF General impact model, together ####

model_general_pf <- lmer(
  GeneralImpactScore ~
    PF_Int_MEAN +
    PF_E_MEAN +
    PF_SD_MEAN +
    PF_RF_MEAN +
    PF_Id_MEAN +
    PF_SF_MEAN +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]
)

#### PF Military impact model, together ####

model_military_pf <- glmer(
  MilitaryImpactScoreBinary ~
    PF_Int_MEAN +
    PF_E_MEAN +
    PF_SD_MEAN +
    PF_RF_MEAN +
    PF_Id_MEAN +
    PF_SF_MEAN +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

tab_model(model_general_pf, model_military_pf)
```

```{r pid5 and pf}
#### PID-5 & PF general impact model, together ####
model_general_pid5_pf <- lmer(
  GeneralImpactScore ~
    PID_Negative_Affect_SUM +
    PID_Detachment_SUM +
    PID_Antagonism_SUM +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +

    PF_Int_MEAN +
    PF_E_MEAN +
    PF_SD_MEAN +
    PF_Id_MEAN +

    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]
)

#### PID-5 & PF military impact model, together ####

model_military_pid5_pf <- glmer(
  MilitaryImpactScoreBinary ~
    PID_Negative_Affect_SUM +
    PID_Detachment_SUM +
    PID_Antagonism_SUM +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +

    PF_Int_MEAN +
    PF_E_MEAN +
    PF_SD_MEAN +
    PF_Id_MEAN +

    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)

tab_model(model_general_pid5_pf, model_military_pid5_pf)
```

# Correlation matrix between personality measures/subscales
```{r personality corr}
apa.cor.table(
  long_df_final %>%
    group_by(ID) %>%
    slice(1) %>%
    ungroup() %>%
    select(
      PF_Int_MEAN, PF_E_MEAN, PF_SD_MEAN, PF_Id_MEAN,
      PID_Negative_Affect_SUM, PID_Detachment_SUM, PID_Antagonism_SUM,
      PID_Disinhibition_SUM, PID_Psychoticism_SUM,
      years_since_discharge, Duration_service
    )
)
```

# Include significant PID-5 personality subscales in main models
```{r models with age and personality}
# Age model with the general impact score and all age groups + personality
main_model_general_per <- lmer(
  GeneralImpactScore ~
    AgeGroup +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +
    years_since_discharge +
    Duration_service +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
)
summary(main_model_general_per)

# Age model with the military impact score and all age groups + personality
main_model_military_per <- glmer(
  MilitaryImpactScoreBinary ~
    AgeGroup +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +
    years_since_discharge +
    Duration_service +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)
summary(main_model_military_per)

# Age model with the general impact score and collapsed age groups + personality
main_model_general_per_collapse <- lmer(
  GeneralImpactScore ~
    AgeGroupCollapsed +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +
    years_since_discharge +
    Duration_service +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
)
summary(main_model_general_per_collapse)

# Age model with the military impact score and collapsed age groups + personality
main_model_military_per_collapse <- glmer(
  MilitaryImpactScoreBinary ~
    AgeGroupCollapsed +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +
    years_since_discharge +
    Duration_service +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)
summary(main_model_military_per_collapse)


tab_model(
  main_model_general_per,
  main_model_military_per,
  main_model_general_per_collapse,
  main_model_military_per_collapse
)
```

# Include event type
```{r models with age and personality and event}
# Cross table for event type (the aggregate created before) and impact (low-frequency..sparse...)
tab1 <- table(
  long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]$AgeGroupCollapsed,
  long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]$MilitaryImpactScoreBinary
)

addmargins(tab1)

tab2 <- table(
  long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]$AgeGroup,
  long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ]$MilitaryImpactScoreBinary
)

addmargins(tab2)


# Age model with the general impact score and all age groups + events + personality
main_model_general_per_event <- lmer(
  GeneralImpactScore ~
    AgeGroup +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +
    EventGroup +
    # years_since_discharge +
    # Duration_service +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
)
summary(main_model_general_per_event)


# Age model with the military impact score and all age groups + events + personality
main_model_military_per_event <- glmer(
  MilitaryImpactScoreBinary ~
    AgeGroup +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +
    EventGroup +
    # years_since_discharge +
    # Duration_service +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial,
  control = glmerControl(optimizer = "bobyqa")
)
summary(main_model_military_per_event)


# Age model with the general impact score and collapsed age groups + events + personality
main_model_general_per_event_collapse <- lmer(
  GeneralImpactScore ~
    AgeGroupCollapsed +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +
    EventGroup +
    # years_since_discharge +
    # Duration_service +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
)
summary(main_model_general_per_event_collapse)

# Age model with the military impact score and collapsed age groups + events + personality
main_model_military_per_event_collapse <- glmer(
  MilitaryImpactScoreBinary ~
    AgeGroupCollapsed +
    PID_Disinhibition_SUM +
    PID_Psychoticism_SUM +
    EventGroup +
    # years_since_discharge +
    # Duration_service +
    (1 | ID),
  data = long_df_final[long_df_final$MilitaryImpactScoreBinary != 3, ],
  family = binomial
)
summary(main_model_military_per_event_collapse)


tab_model(
  main_model_general_per_event,
  main_model_military_per_event,
  main_model_general_per_event_collapse,
  main_model_military_per_event_collapse
)

theme_set(theme_sjplot())

p4 <- plot_model(main_model_general_per_event,
  type = "est", show.values = TRUE, value.offset = 0.3
)

p5 <- plot_model(main_model_military_per_event,
  type = "est", show.values = TRUE, value.offset = 0.3
)

png(paste0("03_Output/General_model_raw_", format(Sys.Date(), "%Y-%m-%d"), ".png"), units = "in", width = 9, height = 5, res = 300)
p4
dev.off()

png(paste0("03_Output/Military_model_raw_", format(Sys.Date(), "%Y-%m-%d"), ".png"), units = "in", width = 9, height = 5, res = 300)
p5
dev.off()
```

